// Sound files mapping for local audio files
export const soundFiles: Record<string, any> = {
  "Adult/Female/Breathing through contractions.wav": require("../../../../assets/sounds/Adult/Female/Breathingthroughcontractions.wav"),
  "Adult/Female/Coughing.wav": require("../../../../assets/sounds/Adult/Female/Coughing.wav"),
  "Adult/Female/Distressed.wav": require("../../../../assets/sounds/Adult/Female/Distressed.wav"),
  "Adult/Female/Hawk.wav": require("../../../../assets/sounds/Adult/Female/Hawk.wav"),
  "Adult/Female/Moaning.wav": require("../../../../assets/sounds/Adult/Female/Moaning.wav"),
  "Adult/Female/No.wav": require("../../../../assets/sounds/Adult/Female/No.wav"),
  "Adult/Female/Ok.wav": require("../../../../assets/sounds/Adult/Female/Ok.wav"),
  "Adult/Female/Pain.wav": require("../../../../assets/sounds/Adult/Female/Pain.wav"),
  "Adult/Female/Pushing - long double.wav": require("../../../../assets/sounds/Adult/Female/Pushinglongdouble.wav"),
  "Adult/Female/Pushing - long.wav": require("../../../../assets/sounds/Adult/Female/Pushinglong.wav"),
  "Adult/Female/Pushing - single.wav": require("../../../../assets/sounds/Adult/Female/Pushingsingle.wav"),
  "Adult/Female/Screaming.wav": require("../../../../assets/sounds/Adult/Female/Screaming.wav"),
  "Adult/Female/Sob breathing (type 2).wav": require("../../../../assets/sounds/Adult/Female/Sobbreathing(type2).wav"),
  "Adult/Female/Sob breathing.wav": require("../../../../assets/sounds/Adult/Female/Sobbreathing.wav"),
  "Adult/Female/Vomiting.wav": require("../../../../assets/sounds/Adult/Female/Vomiting.wav"),
  "Adult/Female/Yes.wav": require("../../../../assets/sounds/Adult/Female/Yes.wav"),
  "Adult/Male/Coughing (long).wav": require("../../../../assets/sounds/Adult/Male/Coughing(long).wav"),
  "Adult/Male/Coughing.wav": require("../../../../assets/sounds/Adult/Male/Coughing.wav"),
  "Adult/Male/Difficult breathing.wav": require("../../../../assets/sounds/Adult/Male/Difficultbreathing.wav"),
  "Adult/Male/Hawk.wav": require("../../../../assets/sounds/Adult/Male/Hawk.wav"),
  "Adult/Male/Moaning (long).wav": require("../../../../assets/sounds/Adult/Male/Moaning(long).wav"),
  "Adult/Male/oaning.wav": require("../../../../assets/sounds/Adult/Male/Moaning.wav"),
  "Adult/Male/No.wav": require("../../../../assets/sounds/Adult/Male/No.wav"),
  "Adult/Male/Ok.wav": require("../../../../assets/sounds/Adult/Male/Ok.wav"),
  "Adult/Male/Screaming (type 2).wav": require("../../../../assets/sounds/Adult/Male/Screaming(type2).wav"),
  "Adult/Male/Screaming.wav": require("../../../../assets/sounds/Adult/Male/Screaming.wav"),
  "Adult/Male/Sob breathing.wav": require("../../../../assets/sounds/Adult/Male/Sobbreathing.wav"),
  "Adult/Male/Vomiting (type 2).wav": require("../../../../assets/sounds/Adult/Male/Vomiting(type2).wav"),
  "Adult/Male/Vomiting (type 3).wav": require("../../../../assets/sounds/Adult/Male/Vomiting(type3).wav"),
  "Adult/Male/Vomiting.wav": require("../../../../assets/sounds/Adult/Male/Vomiting.wav"),
  "Adult/Male/Yes.wav": require("../../../../assets/sounds/Adult/Male/Yes.wav"),
  "Speech/Chest hurts.wav": require("../../../../assets/sounds/Speech/Chesthurts.wav"),
  "Speech/Doc I feel I could die.wav": require("../../../../assets/sounds/Speech/DocIfeelIcoulddie.wav"),
  "Speech/Go away.wav": require("../../../../assets/sounds/Speech/Goaway.wav"),
  "Speech/I don't feel dizzy.wav": require("../../../../assets/sounds/Speech/Idontfeeldizzy.wav"),
  "Speech/I don't feel well.wav": require("../../../../assets/sounds/Speech/Idontfeelwell.wav"),
  "Speech/I feel better now.wav": require("../../../../assets/sounds/Speech/Ifeelbetternow.wav"),
  "Speech/I feel really bad.wav": require("../../../../assets/sounds/Speech/Ifeelreallybad.wav"),
  "Speech/I'm feeling very dizzy.wav": require("../../../../assets/sounds/Speech/Imfeelingverydizzy.wav"),
  "Speech/I'm fine.wav": require("../../../../assets/sounds/Speech/Imfine.wav"),
  "Speech/I'm quite nauseous.wav": require("../../../../assets/sounds/Speech/Imquitenauseous.wav"),
  "Speech/I'm really hungry.wav": require("../../../../assets/sounds/Speech/Imreallyhungry.wav"),
  "Speech/I'm really thirsty.wav": require("../../../../assets/sounds/Speech/Imreallythirsty.wav"),
  "Speech/I'm so sick.wav": require("../../../../assets/sounds/Speech/Imsosick.wav"),
  "Speech/Never had pain like this before.wav": require("../../../../assets/sounds/Speech/Neverhadpainlikethisbefore.wav"),
  "Speech/No allergies.wav": require("../../../../assets/sounds/Speech/Noallergies.wav"),
  "Speech/No diabetes.wav": require("../../../../assets/sounds/Speech/Nodiabetes.wav"),
  "Speech/No lung or cardiac problems.wav": require("../../../../assets/sounds/Speech/Nolungorcardiacproblems.wav"),
  "Speech/No.wav": require("../../../../assets/sounds/Speech/No.wav"),
  "Speech/Pain for 2 hours.wav": require("../../../../assets/sounds/Speech/Painfor2hours.wav"),
  "Speech/Something for this pain.wav": require("../../../../assets/sounds/Speech/Somethingforthispain.wav"),
  "Speech/Thank you.wav": require("../../../../assets/sounds/Speech/Thankyou.wav"),
  "Speech/That helped.wav": require("../../../../assets/sounds/Speech/Thathelped.wav"),
  "Speech/Yes.wav": require("../../../../assets/sounds/Speech/Yes.wav"),
  "Child/Coughing.wav": require("../../../../assets/sounds/Child/Coughing.wav"),
  "Child/Hawk.wav": require("../../../../assets/sounds/Child/Hawk.wav"),
  "Child/Moaning.wav": require("../../../../assets/sounds/Child/Moaning.wav"),
  "Child/No.wav": require("../../../../assets/sounds/Child/No.wav"),
  "Child/Ok.wav": require("../../../../assets/sounds/Child/Ok.wav"),
  "Child/Screaming.wav": require("../../../../assets/sounds/Child/Screaming.wav"),
  "Child/Sob breathing.wav": require("../../../../assets/sounds/Child/Sobbreathing.wav"),
  "Child/Vomiting (type 2).wav": require("../../../../assets/sounds/Child/Vomiting(type2).wav"),
  "Child/Vomiting.wav": require("../../../../assets/sounds/Child/Vomiting.wav"),
  "Child/Yes.wav": require("../../../../assets/sounds/Child/Yes.wav"),
  "Geriatric/Female/Coughing.wav": require("../../../../assets/sounds/Geriatric/Female/Coughing.wav"),
  "Geriatric/Female/Moaning.wav": require("../../../../assets/sounds/Geriatric/Female/Moaning.wav"),
  "Geriatric/Female/No.wav": require("../../../../assets/sounds/Geriatric/Female/No.wav"),
  "Geriatric/Female/Screaming.wav": require("../../../../assets/sounds/Geriatric/Female/Screaming.wav"),
  "Geriatric/Female/Vomiting.wav": require("../../../../assets/sounds/Geriatric/Female/Vomiting.wav"),
  "Geriatric/Female/Yes.wav": require("../../../../assets/sounds/Geriatric/Female/Yes.wav"),
  "Geriatric/Male/Coughing.wav": require("../../../../assets/sounds/Geriatric/Male/Coughing.wav"),
  "Geriatric/Male/Moaning.wav": require("../../../../assets/sounds/Geriatric/Male/Moaning.wav"),
  "Geriatric/Male/No.wav": require("../../../../assets/sounds/Geriatric/Male/No.wav"),
  "Geriatric/Male/Screaming.wav": require("../../../../assets/sounds/Geriatric/Male/Screaming.wav"),
  "Geriatric/Male/Vomiting.wav": require("../../../../assets/sounds/Geriatric/Male/Vomiting.wav"),
  "Geriatric/Male/Yes.wav": require("../../../../assets/sounds/Geriatric/Male/Yes.wav"),
  "Infant/Content.wav": require("../../../../assets/sounds/Infant/Content.wav"),
  "Infant/Cough.wav": require("../../../../assets/sounds/Infant/Cough.wav"),
  "Infant/Grunt.wav": require("../../../../assets/sounds/Infant/Grunt.wav"),
  "Infant/Hawk.wav": require("../../../../assets/sounds/Infant/Hawk.wav"),
  "Infant/Hiccup.wav": require("../../../../assets/sounds/Infant/Hiccup.wav"),
  "Infant/Screaming.wav": require("../../../../assets/sounds/Infant/Screaming.wav"),
  "Infant/Strongcry (type 2).wav": require("../../../../assets/sounds/Infant/Strongcry(type2).wav"),
  "Infant/Strongcry.wav": require("../../../../assets/sounds/Infant/Strongcry.wav"),
  "Infant/Weakcry.wav": require("../../../../assets/sounds/Infant/Weakcry.wav"),
};

// Audio file mapping for server-side streaming
export const audioFileMap: Record<string, string> = {
  "Adult/Female/Breathing through contractions.wav": "adult-female-breathing-contractions",
  "Adult/Female/Coughing.wav": "adult-female-coughing",
  "Adult/Female/Distressed.wav": "adult-female-distressed",
  "Adult/Female/Hawk.wav": "adult-female-hawk",
  "Adult/Female/Moaning.wav": "adult-female-moaning",
  "Adult/Female/No.wav": "adult-female-no",
  "Adult/Female/Ok.wav": "adult-female-ok",
  "Adult/Female/Pain.wav": "adult-female-pain",
  "Adult/Female/Screaming.wav": "adult-female-screaming",
  "Adult/Female/Vomiting.wav": "adult-female-vomiting",
  "Adult/Female/Yes.wav": "adult-female-yes",
  "Adult/Male/Coughing.wav": "adult-male-coughing",
  "Adult/Male/Moaning.wav": "adult-male-moaning",
  "Adult/Male/No.wav": "adult-male-no",
  "Adult/Male/Ok.wav": "adult-male-ok",
  "Adult/Male/Screaming.wav": "adult-male-screaming",
  "Adult/Male/Vomiting.wav": "adult-male-vomiting",
  "Adult/Male/Yes.wav": "adult-male-yes",
  "Child/Coughing.wav": "child-coughing",
  "Child/Moaning.wav": "child-moaning",
  "Child/No.wav": "child-no",
  "Child/Ok.wav": "child-ok",
  "Child/Screaming.wav": "child-screaming",
  "Child/Vomiting.wav": "child-vomiting",
  "Child/Yes.wav": "child-yes",
  // Add more mappings as needed
};
